### ISSUE TITLE
How do i run the c++ brute force code 

### ISSUE THREAD

**Issue by SpottyMickeyv2** [CyanCoding/Brute-Force-Password-Cracker#3]
i tried in visual studio code but in the output its says the name of the file and below that g++ isnt recognized like a internal or external program

**Comment by edcdecl** [comment]
You need a C++ compiler in order to run it.

**Comment by CyanCoding** [comment]
Visual Studio Code can't run C++ programs without the necessary prerequisites on your system. I think it's `gcc g++ buildessential` and maybe a few others. You can look this up online for building and running C++ programs.

I'm closing this as it's not related to the development of this project.
